NUMERICAL_FEATURES = ['escore_bruto_p1_etapa1',
                      'escore_bruto_p2_etapa1',
                      'nota_redacao_etapa1',
                      'escore_bruto_p1_etapa2',
                      'escore_bruto_p2_etapa2',
                      'nota_redacao_etapa2',
                      'escore_bruto_p1_etapa3',
                      'escore_bruto_p2_etapa3',
                      'nota_redacao_etapa3',
                      'argumento_final']

COTAS_COLUMNS =  ['classificacao_final_cotas_negros',
                  'classificacao_final_publicas1',
                  'classificacao_final_publicas2',
                  'classificacao_final_publicas3',
                  'classificacao_final_publicas4',
                  'classificacao_final_publicas5',
                  'classificacao_final_publicas6',
                  'classificacao_final_publicas7',
                  'classificacao_final_publicas8']