sample_approved = {"escore_bruto_p1_etapa1": 0.0,
                   "escore_bruto_p2_etapa1": 29.595,
                   "nota_redacao_etapa1": 7.524,
                   "escore_bruto_p1_etapa2": 4.614,
                   "escore_bruto_p2_etapa2": 19.737,
                   "nota_redacao_etapa2": 7.2,
                   "escore_bruto_p1_etapa3": 2.856,
                   "escore_bruto_p2_etapa3": 35.7,
                   "nota_redacao_etapa3": 7.369,
                   "argumento_final": 14.603,
                   "MATEMÁTICA (BACHARELADO/LICENCIATURA)": 1.0,
                   "cotista": 1.0,
                   "cotas_negros_flag": 0.0,
                   "publicas1_flag": 0.0,
                   "publicas2_flag": 0.0,
                   "publicas3_flag": 0.0,
                   "publicas4_flag": 0.0,
                   "publicas5_flag": 0.0,
                   "publicas6_flag": 0.0,
                   "publicas7_flag": 1.0,
                   "publicas8_flag": 0.0}

sample_not_approved = {"escore_bruto_p1_etapa1": 5.172,
                "escore_bruto_p2_etapa1": 14.653,
                "nota_redacao_etapa1": 6.947,
                "escore_bruto_p1_etapa2": 3.845,
                "escore_bruto_p2_etapa2": 19.994,
                "nota_redacao_etapa2": 7.222,
                "escore_bruto_p1_etapa3": 4.998,
                "escore_bruto_p2_etapa3": 16.66,
                "nota_redacao_etapa3": 8.06,
                "argumento_final": -25.699,
                "2.1.1 CAMPUS  DARCY RIBEIRO – DIURNO  ADMINISTRAÇÃO (BACHARELADO)": 1.0,               
                "cotista": 0.0,
                "cotas_negros_flag": 0.0,
                "publicas1_flag": 0.0,
                "publicas2_flag": 0.0,
                "publicas3_flag": 0.0,
                "publicas4_flag": 0.0,
                "publicas5_flag": 0.0,
                "publicas6_flag": 0.0,
                "publicas7_flag": 0.0,
                "publicas8_flag": 0.0}