sample_approved = {'escore_bruto_p1_etapa1': 1.724,
                    'escore_bruto_p2_etapa1': 57.897,
                    'nota_redacao_etapa1': 6.933,
                    'escore_bruto_p1_etapa2': 2.307,
                    'escore_bruto_p2_etapa2': 62.272,
                    'nota_redacao_etapa2': 8.667,
                    'escore_bruto_p1_etapa3': 4.998,
                    'escore_bruto_p2_etapa3': 57.596,
                    'nota_redacao_etapa3': 9.655,
                    'cotista': 0.0,
                    'cotas_negros_flag': 0.0,
                    'publicas_flag': 0.0,
                    'publicas1_flag': 0.0,
                    'publicas2_flag': 0.0,
                    'publicas3_flag': 0.0,
                    'publicas4_flag': 0.0,
                    'publicas5_flag': 0.0,
                    'publicas6_flag': 0.0,
                    'publicas7_flag': 0.0,
                    'publicas8_flag': 0.0,
                    'ENGENHARIA AMBIENTAL (BACHARELADO)': 1.0}

sample_not_approved = {'escore_bruto_p1_etapa1': 3.448,
                        'escore_bruto_p2_etapa1': 16.376,
                        'nota_redacao_etapa1': 6.069,
                        'escore_bruto_p1_etapa2': 4.614,
                        'escore_bruto_p2_etapa2': 18.967,
                        'nota_redacao_etapa2': 8.1,
                        'escore_bruto_p1_etapa3': 3.094,
                        'escore_bruto_p2_etapa3': 15.231,
                        'nota_redacao_etapa3': 9.143,
                        'cotista': 1.0,
                        'cotas_negros_flag': 1.0,
                        'publicas_flag': 0.0,
                        'publicas1_flag': 0.0,
                        'publicas2_flag': 0.0,
                        'publicas3_flag': 0.0,
                        'publicas4_flag': 0.0,
                        'publicas5_flag': 0.0,
                        'publicas6_flag': 0.0,
                        'publicas7_flag': 0.0,
                        'publicas8_flag': 0.0,
                        'CIÊNCIA POLÍTICA (BACHARELADO)': 1.0}